// <auto-generated />
using System.Diagnostics;
using Agencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agencia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110214949_firstmigration")]
    [DebuggerDisplay($"{{{nameof(GetDebuggerDisplay)}(),nq}}")]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    partial class Firstmigration
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Agencia.Model.AgenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AgenciaURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agencia_url");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destino");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.ToTable("agencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgenciaURL = "https://github.com/nataliarodrxgues/code-and-go-viagens/blob/main/IMG/promo_juntos.jpg",
                            Destino = "Praias",
                            Nome = "Pacote: Alegria Compartilhada",
                            Preco = 3.250m
                        },
                        new
                        {
                            Id = 2,
                            AgenciaURL = "https://github.com/nataliarodrxgues/code-and-go-viagens/blob/main/IMG/promo_casal.jpg",
                            Destino = "Minas Gerais",
                            Nome = "Pacote: Tour do Amor",
                            Preco = 3.390m
                        },
                        new
                        {
                            Id = 3,
                            AgenciaURL = "https://github.com/nataliarodrxgues/code-and-go-viagens/blob/main/IMG/promo_carnaval.jpg",
                            Destino = "Rio de Janeiro",
                            Nome = "Pacote: A Folia que Você Merece!",
                            Preco = 4.150m
                        });
                });
#pragma warning restore 612, 618
        }

        private string GetDebuggerDisplay()
        {
            return ToString();
        }
    }
}
